# New Orleans Crime Stats for 2018
---
## Starter Code to Import Libraries and Load Crime Statistics

The dataset is for all of the Police Reports filed by NOPD officers including incident and supplemental reports containing the item number, location, disposition, signal, charges, offender race, offender gender, offender age, victim age, victim gender, and victim race for the year 2018.

In [1]:
# Dependencies and Setup
from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
# Load the csv into a Pandas Data Frame
crime_2018 = pd.read_csv("Resources/police2018.csv")

# Examine the data frame
crime_2018.head()

,Item_Number,Year,District,Location,Disposition,Signal_Type,Signal_Description,Occurred_Date_Time,Charge_Code,Charge_Description,...,Offender_Age,Offender_Number,Person_Type,Victim_Race,Victim_Gender,Victim_Age,Victim_Number,Victim_Fatal_Status,Hate_Crime,Report_Type
0,D-23482-18,2018,6,23XX Milan St,CLOSED,67,THEFT,4/20/18 7:32,54 186,THEFT,...,42.0,1.0,VICTIM,BLACK,FEMALE,39.0,1.0,Non-fatal,NaN,Supplemental Report
1,E-13975-18,2018,4,45XX Macarthur Bd 69,OPEN,27-29S,ATTEMPTED SUICIDE,5/11/18 16:19,NaN,NaN,...,NaN,NaN,VICTIM,BLACK,MALE,38.0,1.0,Non-fatal,NaN,Incident Report
2,D-34501-18,2018,3,63XX Elysian Fields St,CLOSED,37,AGGRAVATED ASSAULT,4/28/18 23:50,40 966,PROHIBITED ACTS--SCHEDULE I DRUGS,...,19.0,1.0,VICTIM,NaN,NaN,NaN,1.0,Non-fatal,NaN,Incident Report
3,E-12091-18,2018,8,15XX Pauger St,OPEN,67,THEFT,5/10/18 3:30,14 67,THEFT,...,NaN,1.0,VICTIM,BLACK,MALE,61.0,1.0,Non-fatal,NaN,Incident Report
4,I-29004-18,2018,5,9XX Mandeville St,OPEN,21,MISCELLANEOUS INCIDENT,9/23/18 11:30,NaN,NaN,...,NaN,NaN,REPORTING PERSON,BLACK,FEMALE,30.0,1.0,Non-fatal,NaN,Incident Report

In [3]:
# Examine the data types within the dataset
crime_2018.dtypes

Item_Number             object
Year                     int64
District                 int64
Location                object
Disposition             object
Signal_Type             object
Signal_Description      object
Occurred_Date_Time      object
Charge_Code             object
Charge_Description      object
Offender_Race           object
Offender_Gender         object
Offender_Age           float64
Offender_Number        float64
Person_Type             object
Victim_Race             object
Victim_Gender           object
Victim_Age             float64
Victim_Number          float64
Victim_Fatal_Status     object
Hate_Crime              object
Report_Type             object
dtype: object

In [4]:
# Convert Occurred_Date_Time from integer to date time.
crime_2018['Occurred_Date_Time'] = pd.to_datetime(crime_2018['Occurred_Date_Time'], utc=True)
crime_2018['Occurred_Date_Time'].dt.date

0         2018-04-20
1         2018-05-11
2         2018-04-28
3         2018-05-10
4         2018-09-23
             ...
122524    2018-12-26
122525    2018-12-22
122526    2018-12-21
122527    2018-12-25
122528    2018-12-20
Name: Occurred_Date_Time, Length: 122529, dtype: object

In [5]:
# This code replaces the date/time in Occurred_Date_Time column with only the date.
crime_2018["Occurred_Date_Time"] = crime_2018["Occurred_Date_Time"].dt.date
print(crime_2018)

       Item_Number  Year  District                   Location Disposition  \
0       D-23482-18  2018         6              23XX Milan St      CLOSED
1       E-13975-18  2018         4       45XX Macarthur Bd 69        OPEN
2       D-34501-18  2018         3     63XX Elysian Fields St      CLOSED
3       E-12091-18  2018         8             15XX Pauger St        OPEN
4       I-29004-18  2018         5          9XX Mandeville St        OPEN
...            ...   ...       ...                        ...         ...
122524  L-32803-18  2018         5            14XX Jourdan Av        OPEN
122525  L-28470-18  2018         2             81XX Nelson St        OPEN
122526  L-27594-18  2018         6         28XX S Derbigny St        OPEN
122527  L-31983-18  2018         1  14XX Henriette Delille St        OPEN
122528  L-26044-18  2018         2       13XX S Carrollton Av        OPEN

       Signal_Type           Signal_Description Occurred_Date_Time  \
0               67                        THEFT         2018-04-20
1           27-29S            ATTEMPTED SUICIDE         2018-05-11
2               37           AGGRAVATED ASSAULT         2018-04-28
3               67                        THEFT         2018-05-10
4               21       MISCELLANEOUS INCIDENT         2018-09-23
...            ...                          ...                ...
122524          24                      MEDICAL         2018-12-26
122525         62C    SIMPLE BURGLARY (VEHICLE)         2018-12-22
122526         62R  SIMPLE BURGLARY (RESIDENCE)         2018-12-21
122527        103D       DISTURBANCE (DOMESTIC)         2018-12-25
122528          24                      MEDICAL         2018-12-20

       Charge_Code                 Charge_Description  ... Offender_Age  \
0           54 186                              THEFT  ...         42.0
1              NaN                                NaN  ...          NaN
2           40 966  PROHIBITED ACTS--SCHEDULE I DRUGS  ...         19.0
3            14 67                              THEFT  ...          NaN
4              NaN                                NaN  ...          NaN
...            ...                                ...  ...          ...
122524         NaN                                NaN  ...          NaN
122525       14 62                    SIMPLE BURGLARY  ...          NaN
122526       14 62                    SIMPLE BURGLARY  ...          NaN
122527         NaN                                NaN  ...          NaN
122528         NaN                                NaN  ...          NaN

       Offender_Number       Person_Type  Victim_Race Victim_Gender  \
0                  1.0            VICTIM        BLACK        FEMALE
1                  NaN            VICTIM        BLACK          MALE
2                  1.0            VICTIM          NaN           NaN
3                  1.0            VICTIM        BLACK          MALE
4                  NaN  REPORTING PERSON        BLACK        FEMALE
...                ...               ...          ...           ...
122524             NaN            VICTIM        BLACK        FEMALE
122525             1.0            VICTIM        WHITE          MALE
122526             1.0            VICTIM        BLACK        FEMALE
122527             NaN         INTERVIEW        BLACK          MALE
122528             NaN         INTERVIEW        BLACK        FEMALE

       Victim_Age Victim_Number  Victim_Fatal_Status  Hate_Crime  \
0            39.0           1.0            Non-fatal         NaN
1            38.0           1.0            Non-fatal         NaN
2             NaN           1.0            Non-fatal         NaN
3            61.0           1.0            Non-fatal         NaN
4            30.0           1.0            Non-fatal         NaN
...           ...           ...                  ...         ...
122524       80.0           1.0                Fatal         NaN
122525       30.0           1.0            Non-fatal         NaN
122526       58.0           1.0            Non-fatal         NaN
122527       26.0           3.0            Non-fatal         NaN
122528       32.0           1.0            Non-fatal         NaN

                Report_Type
0       Supplemental Report
1           Incident Report
2           Incident Report
3           Incident Report
4           Incident Report
...                     ...
122524      Incident Report
122525      Incident Report
122526      Incident Report
122527      Incident Report
122528      Incident Report

[122529 rows x 22 columns]

In [6]:
# This views the data and conducts column counts.
crime_2018.count()

Item_Number            122529
Year                   122529
District               122529
Location               122529
Disposition            122529
Signal_Type            122529
Signal_Description     122529
Occurred_Date_Time     122529
Charge_Code             57202
Charge_Description      57202
Offender_Race           59007
Offender_Gender         56303
Offender_Age            39457
Offender_Number         77688
Person_Type            118447
Victim_Race             91231
Victim_Gender           91519
Victim_Age              85198
Victim_Number          118447
Victim_Fatal_Status    122529
Hate_Crime                 43
Report_Type            122529
dtype: int64

In [7]:
# This drops duplicates from Item_Number, then stores the changes.
crime_2018.drop_duplicates(keep=False, ignore_index=True, inplace=True)
deduped_crime = crime_2018
deduped_crime.count()

Item_Number            120762
Year                   120762
District               120762
Location               120762
Disposition            120762
Signal_Type            120762
Signal_Description     120762
Occurred_Date_Time     120762
Charge_Code             55638
Charge_Description      55638
Offender_Race           57449
Offender_Gender         54783
Offender_Age            38245
Offender_Number         75957
Person_Type            116680
Victim_Race             90543
Victim_Gender           90831
Victim_Age              84568
Victim_Number          116680
Victim_Fatal_Status    120762
Hate_Crime                 43
Report_Type            120762
dtype: int64

In [10]:
# Remove Miscellaneous Incident from the Signal_Description column
clean_signal =deduped_crime.loc[~deduped_crime["Signal_Description"].str.contains("MISCELLANEOUS INCIDENT")]
clean_signal.head()

,Item_Number,Year,District,Location,Disposition,Signal_Type,Signal_Description,Occurred_Date_Time,Charge_Code,Charge_Description,...,Offender_Age,Offender_Number,Person_Type,Victim_Race,Victim_Gender,Victim_Age,Victim_Number,Victim_Fatal_Status,Hate_Crime,Report_Type
0,D-23482-18,2018,6,23XX Milan St,CLOSED,67,THEFT,2018-04-20,54 186,THEFT,...,42.0,1.0,VICTIM,BLACK,FEMALE,39.0,1.0,Non-fatal,NaN,Supplemental Report
1,E-13975-18,2018,4,45XX Macarthur Bd 69,OPEN,27-29S,ATTEMPTED SUICIDE,2018-05-11,NaN,NaN,...,NaN,NaN,VICTIM,BLACK,MALE,38.0,1.0,Non-fatal,NaN,Incident Report
2,D-34501-18,2018,3,63XX Elysian Fields St,CLOSED,37,AGGRAVATED ASSAULT,2018-04-28,40 966,PROHIBITED ACTS--SCHEDULE I DRUGS,...,19.0,1.0,VICTIM,NaN,NaN,NaN,1.0,Non-fatal,NaN,Incident Report
3,E-12091-18,2018,8,15XX Pauger St,OPEN,67,THEFT,2018-05-10,14 67,THEFT,...,NaN,1.0,VICTIM,BLACK,MALE,61.0,1.0,Non-fatal,NaN,Incident Report
5,D-13290-18,2018,5,19XX N Tonti St,CLOSED,966,DRUG LAW VIOLATION,2018-04-11,14 95.1,POSSESSION OF FIREARM BY FELON,...,31.0,1.0,VICTIM,NaN,NaN,NaN,1.0,Non-fatal,NaN,Incident Report

In [11]:
# Select columns of interest from the DataFrame and save the new DataFrame
# Selected: "Item_Number", "Year", "District", "Signal_Description", "Occurred_Date_Time", & "Offender_Gender". 

reduced_crime_df = clean_signal[["Item_Number", "Year", "District", "Signal_Type","Signal_Description", "Occurred_Date_Time", 
                       "Offender_Gender", "Victim_Fatal_Status"]]
reduced_crime_df.head()

,Item_Number,Year,District,Signal_Type,Signal_Description,Occurred_Date_Time,Offender_Gender,Victim_Fatal_Status
0,D-23482-18,2018,6,67,THEFT,2018-04-20,MALE,Non-fatal
1,E-13975-18,2018,4,27-29S,ATTEMPTED SUICIDE,2018-05-11,NaN,Non-fatal
2,D-34501-18,2018,3,37,AGGRAVATED ASSAULT,2018-04-28,MALE,Non-fatal
3,E-12091-18,2018,8,67,THEFT,2018-05-10,MALE,Non-fatal
5,D-13290-18,2018,5,966,DRUG LAW VIOLATION,2018-04-11,MALE,Non-fatal

In [12]:
# Count how many incidents occurred
crime_type = reduced_crime_df ["Signal_Description"].value_counts()
crime_type

DISTURBANCE (DOMESTIC)         19057
DRUG LAW VIOLATION              6949
SIMPLE BURGLARY (VEHICLE)       6500
SHOPLIFTING                     6379
SIMPLE BATTERY (DOMESTIC)       6301
                               ...
PUBLIC DRUNK                       1
TAKING TEMPORARY POSSESSION        1
HOMICIDE (DOMESTIC)                1
SILENT ROBBERY ALARM               1
FIREWORKS                          1
Name: Signal_Description, Length: 163, dtype: int64

In [15]:
# Convert the Signal_Description into a DataFrame and retrieve the top ten offenses.
crime_specific_df = pd.DataFrame(crime_type)
crime_filtered = crime_specific_df.nlargest(10, columns=["Signal_Description"], keep= "all")
crime_filtered

                           Signal_Description
DISTURBANCE (DOMESTIC)                  19057
DRUG LAW VIOLATION                       6949
SIMPLE BURGLARY (VEHICLE)                6500
SHOPLIFTING                              6379
SIMPLE BATTERY (DOMESTIC)                6301
THEFT                                    6027
DISTURBANCE                              5821
SIMPLE BATTERY                           5147
SIMPLE CRIMINAL DAMAGE                   4412
FUGITIVE ATTACHMENT                      3835

In [14]:
#top_ten = ["DISTURBANCE (DOMESTIC)", "DRUG LAW VIOLATION", "SIMPLE BURGLARY (VEHICLE)", "SHOPLIFTING",
           #"SIMPLE BATTERY (DOMESTIC)","THEFT","DISTURBANCE", "SIMPLE BATTERY","SIMPLE CRIMINAL DAMAGE",
          #"FUGITIVE ATTACHMENT"]
#crime_type = []

#for crime in top_ten:
    # Locate the districts for each of the top ten offenses
    #final_district = reduced_crime_df.loc[reduced_crime_df["Signal_Description"] == crime, "District"]
    #final_district_list.append(final_district)
    #print(crime_type)

In [ ]:
#def crime_data():
    #dict_copy = reduced_crime_df.to_dict("records")
    #Signal_Descriptions = []
    #for r in dict_copy:
        #Signal_Descriptions.append(r["Signal_Description"])
        
#Signal_Descriptions